from robotcode.server.types import InitializeParams


def test_something():
    params = {
        "processId": 8656,
        "clientInfo": {"name": "Visual Studio Code", "version": "1.52.1"},
        "locale": "de",
        "rootPath": "c:\\tmp\\robottest",
        "rootUri": "file:///c%3A/tmp/robottest",
        "capabilities": {
            "workspace": {
                "applyEdit": True,
                "workspaceEdit": {
                    "documentChanges": True,
                    "resourceOperations": ["create", "rename", "delete"],
                    "failureHandling": "textOnlyTransactional",
                    "normalizesLineEndings": True,
                    "changeAnnotationSupport": {"groupsOnLabel": True},
                },
                "didChangeConfiguration": {"dynamicRegistration": True},
                "didChangeWatchedFiles": {"dynamicRegistration": True},
                "symbol": {
                    "dynamicRegistration": True,
                    "symbolKind": {
                        "valueSet": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                        ]
                    },
                    "tagSupport": {"valueSet": [1]},
                },
                "codeLens": {"refreshSupport": True},
                "executeCommand": {"dynamicRegistration": True},
                "configuration": True,
                "workspaceFolders": True,
                "semanticTokens": {"refreshSupport": True},
                "fileOperations": {
                    "dynamicRegistration": True,
                    "didCreate": True,
                    "didRename": True,
                    "didDelete": True,
                    "willCreate": True,
                    "willRename": True,
                    "willDelete": True,
                },
            },
            "textDocument": {
                "publishDiagnostics": {
                    "relatedInformation": True,
                    "versionSupport": False,
                    "tagSupport": {"valueSet": [1, 2]},
                    "codeDescriptionSupport": True,
                    "dataSupport": True,
                },
                "synchronization": {
                    "dynamicRegistration": True,
                    "willSave": True,
                    "willSaveWaitUntil": True,
                    "didSave": True,
                },
                "completion": {
                    "dynamicRegistration": True,
                    "contextSupport": True,
                    "completionItem": {
                        "snippetSupport": True,
                        "commitCharactersSupport": True,
                        "documentationFormat": ["markdown", "plaintext"],
                        "deprecatedSupport": True,
                        "preselectSupport": True,
                        "tagSupport": {"valueSet": [1]},
                        "insertReplaceSupport": True,
                        "resolveSupport": {"properties": ["documentation", "detail", "additionalTextEdits"]},
                        "insertTextModeSupport": {"valueSet": [1, 2]},
                    },
                    "completionItemKind": {
                        "valueSet": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                        ]
                    },
                },
                "hover": {
                    "dynamicRegistration": True,
                    "contentFormat": ["markdown", "plaintext"],
                },
                "signatureHelp": {
                    "dynamicRegistration": True,
                    "signatureInformation": {
                        "documentationFormat": ["markdown", "plaintext"],
                        "parameterInformation": {"labelOffsetSupport": True},
                        "activeParameterSupport": True,
                    },
                    "contextSupport": True,
                },
                "definition": {"dynamicRegistration": True, "linkSupport": True},
                "references": {"dynamicRegistration": True},
                "documentHighlight": {"dynamicRegistration": True},
                "documentSymbol": {
                    "dynamicRegistration": True,
                    "symbolKind": {
                        "valueSet": [
                            1,
                            2,
                            3,
                            4,
                            5,
                            6,
                            7,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            14,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                        ]
                    },
                    "hierarchicalDocumentSymbolSupport": True,
                    "tagSupport": {"valueSet": [1]},
                    "labelSupport": True,
                },
                "codeAction": {
                    "dynamicRegistration": True,
                    "isPreferredSupport": True,
                    "disabledSupport": True,
                    "dataSupport": True,
                    "resolveSupport": {"properties": ["edit"]},
                    "codeActionLiteralSupport": {
                        "codeActionKind": {
                            "valueSet": [
                                "",
                                "quickfix",
                                "refactor",
                                "refactor.extract",
                                "refactor.inline",
                                "refactor.rewrite",
                                "source",
                                "source.organizeImports",
                            ]
                        }
                    },
                    "honorsChangeAnnotations": False,
                },
                "codeLens": {"dynamicRegistration": True},
                "formatting": {"dynamicRegistration": True},
                "rangeFormatting": {"dynamicRegistration": True},
                "onTypeFormatting": {"dynamicRegistration": True},
                "rename": {
                    "dynamicRegistration": True,
                    "prepareSupport": True,
                    "prepareSupportDefaultBehavior": 1,
                    "honorsChangeAnnotations": True,
                },
                "documentLink": {"dynamicRegistration": True, "tooltipSupport": True},
                "typeDefinition": {"dynamicRegistration": True, "linkSupport": True},
                "implementation": {"dynamicRegistration": True, "linkSupport": True},
                "colorProvider": {"dynamicRegistration": True},
                "foldingRange": {
                    "dynamicRegistration": True,
                    "rangeLimit": 5000,
                    "lineFoldingOnly": True,
                },
                "declaration": {"dynamicRegistration": True, "linkSupport": True},
                "selectionRange": {"dynamicRegistration": True},
                "callHierarchy": {"dynamicRegistration": True},
                "semanticTokens": {
                    "dynamicRegistration": True,
                    "tokenTypes": [
                        "namespace",
                        "type",
                        "class",
                        "enum",
                        "interface",
                        "struct",
                        "typeParameter",
                        "parameter",
                        "variable",
                        "property",
                        "enumMember",
                        "event",
                        "function",
                        "method",
                        "macro",
                        "keyword",
                        "modifier",
                        "comment",
                        "string",
                        "number",
                        "regexp",
                        "operator",
                    ],
                    "tokenModifiers": [
                        "declaration",
                        "definition",
                        "readonly",
                        "static",
                        "deprecated",
                        "abstract",
                        "async",
                        "modification",
                        "documentation",
                        "defaultLibrary",
                    ],
                    "formats": ["relative"],
                    "requests": {"range": True, "full": {"delta": True}},
                    "multilineTokenSupport": False,
                    "overlappingTokenSupport": False,
                },
                "linkedEditingRange": {"dynamicRegistration": True},
            },
            "window": {
                "showMessage": {"messageActionItem": {"additionalPropertiesSupport": True}},
                "showDocument": {"support": True},
                "workDoneProgress": True,
            },
            "general": {
                "regularExpressions": {"engine": "ECMAScript", "version": "ES2020"},
                "markdown": {"parser": "marked", "version": "1.1.0"},
            },
        },
        "trace": "off",
        "workspaceFolders": [{"uri": "file:///c%3A/tmp/robottest", "name": "robottest"}],        
    }

    p = InitializeParams(**params)

    new_params = p.dict(by_alias=True, exclude_none=True, exclude_unset=True)

    assert new_params == params
