[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "robotcode-core"
description = 'Some core classes for RobotCode'
readme = { "file" = "README.md", "content-type" = "text/markdown" }
requires-python = ">=3.8"
license = {text = "Apache-2.0"}
keywords = []
authors = [{ name = "Daniel Biehl", email = "dbiehl@live.de" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Operating System :: OS Independent",
  "Topic :: Utilities",
  "Typing :: Typed",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Tool",
]
dependencies = ["typing-extensions>=4.4.0"]
dynamic = ["version"]

[project.urls]
Homepage = "https://robotcode.io"
Donate = "https://opencollective.com/robotcode"
Documentation = "https://github.com/robotcodedev/robotcode#readme"
Changelog = "https://github.com/robotcodedev/robotcode/blob/main/CHANGELOG.md"
Issues = "https://github.com/robotcodedev/robotcode/issues"
Source = "https://github.com/robotcodedev/robotcode"

[tool.hatch.version]
path = "src/robotcode/core/__version__.py"

[tool.hatch.build]
dev-mode-dirs = ["src"]

[tool.hatch.build.targets.wheel]
only-include = ["src/robotcode"]
sources = ["src"]

[tool.hatch.build.targets.sdist]
only-include = ["src"]

[tool.hatch.envs.build]
detached = true
python = "38"

[tool.mypy]
python_version = "3.8"
strict = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
warn_unreachable = true
implicit_reexport = false
implicit_optional = true
disallow_untyped_decorators = false
disallow_subclassing_any = false
exclude = [
  '^\.mypy_cache/',
  '^\.venv/',
  '^\.hatch/',
  "^build/",
  "^dist/",
  "^out/",
  "^playground/",
  "^scripts/",
  "^bundled/libs/",
]
mypy_path = [
  "typings",
  "src",
]
explicit_package_bases = true
namespace_packages = true
# allow_untyped_calls = true


[[tool.mypy.overrides]]
module = [
  "robot.*",
  "robotremoteserver.*",
  "debugpy.*",
  "robotidy.*",
  "robocop.*",
  "pluggy",
]
ignore_missing_imports = true
