[versions]
# libraries
kotlinxSerialization = "1.9.0"
junit = "4.13.2"

# plugins
changelog = "2.5.0"
intelliJPlatForm = "2.19.0"
kotlin = "2.4.20"
kover = "0.9.11"

[libraries.kotlinxSerialization]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-json"
version.ref = "kotlinxSerialization"

[libraries.junit]
group = "junit"
name = "junit"
version.ref = "junit"

[plugins.changelog]
id = "org.jetbrains.changelog"
version.ref = "changelog"

[plugins.intelliJPlatForm]
id = "org.jetbrains.intellij.platform"
version.ref = "intelliJPlatForm"

[plugins.kotlin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.kover]
id = "org.jetbrains.kotlinx.kover"
version.ref = "kover"

[plugins.kotlinSerialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin"
